### ISSUE TITLE
Telegraf test should be optional

### ISSUE THREAD

**Issue by kishorenc** [jamescarr/ansible-role-telegraf#6]
If a telegraf input depends on the existence of a service (e.g. zookeeper), the test fails:

```
TASK [jamescarr.telegraf : verify generated telegraf config] *******************
fatal: [zookeeper]: FAILED! => {"changed": true, "cmd": "/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -test", "delta": "0:00:00.022639", "end": "2016-09-08 10:45:30.549514", "failed": true, "rc": 1, "start": "2016-09-08 10:45:30.526875", "stderr": "dial tcp 127.0.0.1:2181: getsockopt: connection refused\n2016/09/08 10:45:30 dial tcp 127.0.0.1:2181: getsockopt: connection refused", "stdout": "* Plugin: zookeeper, Collection 1", "stdout_lines": ["* Plugin: zookeeper, Collection 1"], "warnings": []}
```

This makes it impossible to use this role for such inputs.

**Comment by jamescarr** [comment]
Yeah let's disable that and do a toml check.

**Comment by jamescarr** [comment]
It seems like this feature really needs to be split into three pieces:
- make the test optional
- do a toml syntax check on the config file after it is rendered. 
- do the config test before telegraf actually starts

**Comment by jamescarr** [comment]
Now made optional via `telegraf_verify_config`
